# Generated by Django 3.1.8 on 2021-05-27 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210526_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='video',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(default=django.utils.timezone.now, max_length=750),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=750),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
