# Generated by Django 3.1.8 on 2021-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20210527_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(default='', max_length=750, null=True),
        ),
    ]
