# Generated by Django 3.1.8 on 2021-05-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20210527_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Anonymous', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(default=None, max_length=750, null=True),
        ),
    ]
