# Generated by Django 3.1.8 on 2021-05-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20210527_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, default=None, max_length=750, null=True),
        ),
    ]
